language: php

before_script:
  - composer self-update
  - composer install --dev --prefer-dist

script:
  - vendor/bin/phpcs --warning-severity=0 --standard=PSR2 src
  - vendor/bin/phpunit tests

php:
  - 5.6.6
